### ISSUE TITLE
custom_components/victron/const.py fault dimension

### ISSUE THREAD

**Issue by Saarlothri** [sfstar/hass-victron#114]
custom_components/victron/const.py Line 557 Dimension should be Watt not KiloWatt

**Comment by sfstar** [comment]
The positioning of lines in the const.py file have shifted since August of last year.
Therefore, I'm not completely sure which entity is being referenced.
However, since the pvinverter registers have been patched with the same exact underlying issue I will close this issue assuming it to have been completed in release v0.1.7.
Feel free to re-open, if the issue persist after updating.
