### ISSUE TITLE
Writing data from the Tibber integration

### ISSUE THREAD

**Issue by rodwalker** [sfstar/hass-victron#145]
I have a Multiplus2 without an external Grid meter, and no easy possibility to install and connect one. I have a pseudo-smart meter provided by a Tibber pulse, and hope to use this as the grid meter. There are several ways to do this, some more advisable than others. My python powers are too weak to make it work reliably on the Venus OS directly, so am looking for alternatives where smart people already did the tricky bits.
I have the Tibber integration which reads the Tibber Pulse meter values every 2s or so. I also installed this Victron integration, and see that I can write values into the MP2 dbus.
I would need the "power" and " power production" values from Tibber to be written to the Victron "System grid L1,2,3" in real-time, every couple of seconds (actually (power- powerproduction)/3 to each phase). It is not a disaster if this stops working for some time, so long as it fills zeros by default.
Do you think this is something where hass-victron could help, or would you recommend another way? The next step is to automate ESS charge and discharge based on on the day-ahead price, weather forecast, and other things HA might have access to, so it does seem to be the right place from that perspective. Also using the Victron provided interfaces, rather than hacking around on the VenusOS seems more sustainable.
I am more the enthusiastic beta-tester than python developer, but I might be able to fill in some code if you give tips. I`m very new to HA.

Cheers,
Rod.

**Comment by sfstar** [comment]
Hello @rodwalker,

Unfortunately this is not something this integration is able to help you with.
Each integration covers a "core" purpose, namely making getting and interacting with an external device/endpoint possible in HA.
Creating ESS functionality in HASS-victron would go outside the bounds of what an integration is supposed to do.
However, you could use the data returned by this integration and the tibber integration to make an automation in HA (or node red) to automatically populate the registers for the victron power point tracking.

It would require some mathmatics however, since the more the multiplus produces the less the meter is going to display as being consumed and vice versa.
Next to there being a delay (updating every second results in the system not being able to track 0 watt power consumption (based on my experience with ESS).
I've recently installed an EM540 for my new 3-phase connection.
The best thing would be to either look into the placement of an external grid meter like the em540 (perhaps with zigbee transmitters if wiring is an issue) or placing your loads behind the MP2's so that the MP2's can track how much power is going through AC-IN.

Placing your loads behind the MP2 also has the benefit of power backup if there were to be a grid outage.

For now I will close this issue as won't fix since the solutions are outside the integrations scope
