### ISSUE TITLE
dcsource starter voltage Wrong value show 1.26 V instead of 12.6 V

### ISSUE THREAD

**Issue by Next9999** [sfstar/hass-victron#27]
dcsource starter voltage Wrong value show 1.26 V instead of 12.6 V

**Comment by sfstar** [comment]
thank you for reporting this issue.
According to the victron gx modbus specification the scalefactor should be 100.
Which this integrations configuration reflects (see screenshots)
<img width="1221" alt="Screenshot 2023-02-01 at 19 02 51" src="https://user-images.githubusercontent.com/6717280/216125964-a1e9114f-2427-45bb-90be-a1936f00c2d2.png">

Although it seems that victron has either a definition or a specification bug for this to result in 1.26v instead of the 12.6v
Currently I'm still investigating whether I can get into contact with victron to get some clarification since this doesn't seem to be the first incorrect definition or even a buggy value being returned.

**Comment by sfstar** [comment]
The issue has been shipped in the latest release (v0.3.0) closing issue as resolved.
Feel free to re-open if the issue persists with the v0.3.0 release
