### ISSUE TITLE
Silly question - old FW 2.73 on Cerbo GX and missing devices in HA

### ISSUE THREAD

**Issue by kucerazdenek** [sfstar/hass-victron#84]
I am managing two victron installations in HA, one is mine, Cerbo GX FW 2.93, everything works smoothly, no issues.
Few days ago, vendor installed PV to my neighbors in very same configuration as I have (1x Fronius, 3x Victron Multiplus 3000, Cerbo GX, Pylontech batteries). All devices have recent FW except Cerbo which vendor forgot to upgrade and currently is on FW 2.73.
When I installed victron integration and did the scan on my neighbor installation, I am missing following devices in HA (even they are shown in Cerbo Remote Console)
- ID 30 - victronenergy.grid
- ID 227 - victronenergy.vebus

Rest, (ID 225 - pylontech, ID 20 - pvinverter and ID 100 - settings) works fine. 
I know vendor has to update Cerbo to newer FW,  but would like to kindly ask you if someone had similar experience and I can expect that after FW upgrade it will work correctly, or this might be caused by some other issue. 
Attaching debug log from victron integration, it just states that no registers found for those devices (ID 30, ID 227)
[home-assistant_victron_2023-06-12T18-16-52.628Z.log](https://github.com/sfstar/hass-victron/files/11732113/home-assistant_victron_2023-06-12T18-16-52.628Z.log)

In VRM Console I see them correctly:
![image](https://github.com/sfstar/hass-victron/assets/121700009/63d3839c-38b6-4875-bd50-993d4160881b)

**Comment by sfstar** [comment]
Thank you for opening this issue. (and providing the level of detail)
When I originally started work on this integration I made the assumption that nobody would be having 2 GX devices they wanted to integrate into the same home assistant instance (with this being a local integration and 1 GX device enabling almost infinite future extensions to a given system).
However, this assumption was clearly wrong since you opened this issue (no worries 😉)

If you don't mind me asking Is the connection to your neighbours installation in essence "local" (either on the same lan, point-to-point or using a vpn to create a "local" network over te internet?

Since the integration isn't (currently) completely compatible with this use case I believe that your issue might be stemming from your own installation also exposing a grid device on modbus ID 30 and a vebus endpoint on 227.
Could you check if the ID 30 and id 227 are the overlapping between the instances? (And if so, whether there are any other overlapping ID's).
It's my assumption that the 2 installations use different modbus unit (slave) id's for all other devices but the vebus and grid meter endpoints.
Since, the integration uses the unit id to register an entity ID this would result in an entity_id clash meaning that the entities coming from the 2nd configuration instance wouldn't be able to be registered and would therefore be missing.

**Comment by kucerazdenek** [comment]
It definitely was caused by 2.73 FW
